### ISSUE TITLE
ADLS/WASB/S3 enabled configurations are not honored

### ISSUE THREAD

**Issue by xiaoyongzhu** [feathr-ai/feathr#341]
Currently we have configurations in the YAML file to configure whether users use ADLS/WASB/S3 to ingest offline stores etc. However they are not honored (i.e. Feathr will still try to read S3 section even it's set to False). We'd better fix this.

**Comment by jainr** [comment]
Can you add more details to the ticket please?

**Comment by xiaoyongzhu** [comment]
A good example is for monitoring:

```
monitoring:
  database:
    sql:
      url: 'jdbc:postgresql://featuremonitoring.postgres.database.azure.com:5432/postgres'
      user: "demo"
```

If the end user is not using the monitoring config, the configs are not appended to the spark job:


https://github.com/linkedin/feathr/blob/main/feathr_project/feathr/client.py#L609-L612
